# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "White Rum")
Ingredient.create(name: "Sugar Syrup")
Ingredient.create(name: "Lime Juice")
Ingredient.create(name: "Mint sprigs")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Dry Vermouth")
Ingredient.create(name: "Lemon twist")
Ingredient.create(name: "Bourbon")
Ingredient.create(name: "Angostura Bitters")
Ingredient.create(name: "Orange Bitters")
Ingredient.create(name: "Sugar")
Ingredient.create(name: "Orange peel")
Ingredient.create(name: "Crème de Mure")
Ingredient.create(name: "Lemon Juice")
Ingredient.create(name: "Sugar Syrup")
Ingredient.create(name: "Blackberry")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Lime Juice")
Ingredient.create(name: "Simple Syrup")
Ingredient.create(name: "salt")
Ingredient.create(name: "Peppered Vodka")
Ingredient.create(name: "Sweet Vermouth")
Ingredient.create(name: "Tomato Juice")
Ingredient.create(name: "Red Wine")
Ingredient.create(name: "Anejo Rum")
Ingredient.create(name: "Lime wedges")
Ingredient.create(name: "Cola")
Ingredient.create(name: "Vanilla Vodka")
Ingredient.create(name: "Kahlúa")
Ingredient.create(name: "Double Espresso")
Ingredient.create(name: "Coffee Beans")

